_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
