Train:
  dataset:
    name: SimpleDataSet
    data_dir: ../
    label_file_list:
    - ../CCPD/cropped/train_labels_cleaned.csv
    delimiter: ','
    transforms:
    - DecodeImage:
        img_mode: BGR
        to_rgb: true
        channel_first: true
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - NormalizeImage:
        std:
        - 0.5
        - 0.5
        - 0.5
        mean:
        - 0.5
        - 0.5
        - 0.5
        scale: 0.007843
    - ToCHWImage: {}
    - KeepKeys:
        keep_keys:
        - image
        - label
  loader:
    shuffle: true
    drop_last: true
    batch_size_per_card: 32
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../
    label_file_list:
    - ../CCPD/cropped/val_labels_cleaned.csv
    delimiter: ','
    transforms:
    - DecodeImage:
        img_mode: BGR
        to_rgb: true
        channel_first: true
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - NormalizeImage:
        std:
        - 0.5
        - 0.5
        - 0.5
        mean:
        - 0.5
        - 0.5
        - 0.5
        scale: 0.007843
    - ToCHWImage: {}
    - KeepKeys:
        keep_keys:
        - image
        - label
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 32
    num_workers: 4
Global:
  image_shape:
  - 3
  - 32
  - 320
  use_gpu: false
  epoch_num: 30
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: ./ocr_output
  save_epoch_step: 5
  eval_batch_step:
  - 2000
  - 2000
  character_dict_path: ./chars.txt
  character_type: ch
  max_text_length: 10
  pretrained_model: null
  checkpoints: null
  save_inference_dir: ./inference
  use_space_char: false
Architecture:
  model_type: rec
  algorithm: CRNN
  Transform: null
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 1.0e-05
PostProcess:
  name: CTCLabelDecode
  character_dict_path: ./chars.txt
Loss:
  name: CTCLoss
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
  regularizer:
    name: L2
    factor: 1.0e-05
Metric:
  name: RecMetric
  main_indicator: acc
profiler_options: null
